name: Get tag or nothing
description: Get tag name from GITHUB_REF environment variable
branding:
  icon: tag
  color: gray-dark
inputs:
  env_var_name:
    required: false
    default: 'VERSION'
    description: Environment variable to export the version tag to
  strip_v:
    required: false
    default: false
    description: Whether to strip "v" from the tag or not
outputs:
  tag:
    description: Git tag name
runs:
  using: node12
  main: main.js
